### ISSUE TITLE
solution exercise 8_github_rstudio/tutorial.md

### ISSUE THREAD

**Issue by abotzki** [vibbits/training-material#97]
Hi @tmuylder solution at the end of exercise github_rstudio is rendered but seems empty. 

![afbeelding](https://user-images.githubusercontent.com/38151284/84686520-67a53400-af3c-11ea-8a1f-1ca144ac970f.png)

**Comment by tmuylder** [comment]
Now I know that you followed the course to the end ;).

**Comment by tmuylder** [comment]
Done
